### ISSUE TITLE
Potential security problem(s)

### ISSUE THREAD

**Issue by intrigus-lgtm** [obiba/obiba-commons#43]
Hi, could you please create a new [draft security advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) and 
[invite me](https://help.github.com/en/github/managing-security-vulnerabilities/adding-a-collaborator-to-a-security-advisory) to it?
Any other private communication channel would also be fine.
I have a question to a potential security problem.

**Comment by ymarcon** [comment]
Hi, you can send an email to dev@obiba.org

**Comment by intrigus-lgtm** [comment]
Sent a mail.
